FCEnable: true
VehNum: 3

# Direct graph matrix
DGMat: [0, 1, 1, 1, 0, 1, 1, 1, 0]

# Gain matrix
GMat: [0, 0.0005, 0.0002, 0.0003, 0, 0.0008, 0.0006, 0.0003, 0]

# Formation distances matrix
FormX: [0, 3, 1.5, -3, 0, -1.5, -1.5, 1.5, 0]
FormY: [0, 0, 3, 0, 0, 3, -3, -3, 0]


