# line with distance between vehicles = 1 in x direction
FormLineX: [0,1,2,-1,0,1,-2,-1,0]
FormLineY: [0,0,0,0,0,0,0,0,0]

# desired distance between vehicles
FormDist: 1.3

# current activity threshold
deltaPhi: 0.1
