VehNum: 3

# Direct graph matrix
DGMat: [0, 1, 1, 1, 0, 1, 1, 1, 0]

# Velocity gain
gamma: 0.1

# Sampling time for yaw orientation rate 
Ts: 0.7

# max speed
MaxSpeed: 0.5

# use external DP controller
UseExtCon: True
kdp: 0.5

UseRepel: True
# Force repeling controller gain
kf: 3.5
# Force correction factor
kd: 0.0
# Force vector corr factor
ni: 0.5
# repel radius
rf: 2.0

# Gain matrix
GMat: [0, 0.08, 0.08, 0.08, 0, 0.08, 0.08, 0.08, 0]

# Formation distances matrix
FormX: [0, 3, 1.5, -3, 0, -1.5, -1.5, 1.5, 0]
FormY: [0, 0, 3, 0, 0, 3, -3, -3, 0]


